.\" Manpage for table_tennis
.\" Contact thorsten.johannvorderbrueggen@t-online.de to correct errors or typos.
.TH table_tennis 1 "19 Oct 2017" "0.0.1" "table_tennis man page"
.SH NAME
table_tennis
\-\- the table_tennis
.SH SYNOPSIS
.PP
.SH DESCRIPTION
This functions are part of the
.BR tbd
(https://github.com/tjohann/tbd)
.PP
The table_tennis game
.PP
.SH FILES
.BR table_tennis.c
\- function implementation
.br
.BR table_tennis.h
\- interface header
.br
.PP
.SH OPTIONS
None
.PP
.SH BUGS
No known bugs
.PP
.SH "SEE ALSO"
.BR tbd (1)
.PP
.BR tbd(3)
.PP
.SH AUTHOR
Thorsten Johannvorderbrueggen
.br
Email: \fB<thorsten.johannvorderbrueggen@t-online.de> \fP

